name: Download VIP UDP CUSTOM Files Daily

on:
  schedule:
    - cron: '0 0 * * *'  # تشغيل يومي عند منتصف الليل بتوقيت UTC
  workflow_dispatch:

jobs:
  download_files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create target directory
        run: mkdir -p "assets/assets/config"

      - name: Download files
        working-directory: assets/assets/config
        run: |
          curl -L "https://drive.usercontent.google.com/download?id=1802K0kHeVuqPodww2976cFwD34SXC9ly&export=download&authuser=0" -o "VIP UDP CUSTOM1.hc"
          curl -L "https://drive.usercontent.google.com/download?id=1TGxP8IE2vckczywoxpDTkNEpM6k05HFQ&export=download&authuser=0" -o "VIP UDP CUSTOM2.hc"
          curl -L "https://drive.usercontent.google.com/download?id=1el3YYW-iUce33-N2w2u_krvEWa4YmFfC&export=download&authuser=0" -o "VIP UDP CUSTOM3.hc"
          curl -L "https://drive.usercontent.google.com/download?id=1UAUXHLWloXzKo9rJRO2kgQB6k0Zv_kpp&export=download&authuser=0" -o "VIP UDP CUSTOM4.hc"
          curl -L "https://drive.usercontent.google.com/download?id=1cWAz5b5kfqoMECIcq0eG0VVw3nAE_a5A&export=download&authuser=0" -o "VIP UDP CUSTOM5.hc"
          curl -L "https://drive.usercontent.google.com/download?id=1LYpErOorXxXLrRWa6DczMFI20N6lzNz3&export=download&authuser=0" -o "VIP UDP CUSTOM6.hc"

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push updated files
        run: |
          git add "assets/assets/config"
          git commit -m "Update VIP UDP CUSTOM files in config folder" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
